### ISSUE TITLE
Multiple predefined values for capabilities

### ISSUE THREAD

**Issue by mikematton** [ebu/ame-cards#1]
There should be good support in the schema for multiple predefined values for capabilities in the schema. Example of what we intend to obtain:
`<Capability xsi:type="audioLanguageCapabilityType">`
`  <Value>urn:iso:std:iso:639:-1</Value>`
`  <Value>urn:iso:std:iso:639:-2</Value>`
`  <Type>http://ebu.io/fims/ame/capabilities/audio/language</Type>`
`</Capability>`

**Comment by wbailer** [comment]
Resolved with enumeration
